{{- if .Values.keycloak.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.keycloak.name }}-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "shelfinity.keycloak.labels" . | nindent 4 }}
data:
  KC_DB: {{ .Values.keycloak.config.database.vendor }}
  KC_DB_URL: "jdbc:postgresql://{{ .Values.keycloak.config.database.host }}:{{ .Values.keycloak.config.database.port }}/{{ .Values.keycloak.config.database.name }}"
  KC_DB_USERNAME: {{ .Values.keycloak.config.database.username }}
  KC_HOSTNAME_STRICT: "false"
  KC_HOSTNAME_STRICT_HTTPS: "false"
  KC_HTTP_ENABLED: "true"
  KC_PROXY: "edge"
{{- end }}

# Made with Bob
