{{- if .Values.keycloak.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.keycloak.name }}-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "shelfinity.keycloak.labels" . | nindent 4 }}
type: Opaque
stringData:
  KEYCLOAK_ADMIN: {{ .Values.keycloak.config.adminUser }}
  KEYCLOAK_ADMIN_PASSWORD: {{ randAlphaNum 16 | b64enc | quote }}
  KC_DB_PASSWORD: {{ randAlphaNum 16 | b64enc | quote }}
{{- end }}

# Made with Bob
