{{- if .Values.security.networkPolicy.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.database.name }}-netpol
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "shelfinity.database.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "shelfinity.database.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          {{- include "shelfinity.backend.selectorLabels" . | nindent 10 }}
    - podSelector:
        matchLabels:
          {{- include "shelfinity.keycloak.selectorLabels" . | nindent 10 }}
    ports:
    - protocol: TCP
      port: 5432
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.keycloak.name }}-netpol
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "shelfinity.keycloak.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "shelfinity.keycloak.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          {{- include "shelfinity.backend.selectorLabels" . | nindent 10 }}
    - podSelector:
        matchLabels:
          {{- include "shelfinity.frontend.selectorLabels" . | nindent 10 }}
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          app: router
    ports:
    - protocol: TCP
      port: 8080
    - protocol: TCP
      port: 8443
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.backend.name }}-netpol
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "shelfinity.backend.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "shelfinity.backend.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          {{- include "shelfinity.frontend.selectorLabels" . | nindent 10 }}
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          app: router
    ports:
    - protocol: TCP
      port: 9080
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.frontend.name }}-netpol
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "shelfinity.frontend.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "shelfinity.frontend.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          app: router
    ports:
    - protocol: TCP
      port: 80
{{- end }}

# Made with Bob
