{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backend.name }}-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "shelfinity.backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: {{ randAlphaNum 16 | b64enc | quote }}
{{- end }}

# Made with Bob
