{{- if .Values.frontend.enabled }}
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ .Values.frontend.image.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "shelfinity.frontend.labels" . | nindent 4 }}
spec:
  lookupPolicy:
    local: true
{{- end }}

# Made with Bob
